### ISSUE TITLE
Values can only be strings

### ISSUE THREAD

**Issue by joto** [babykarte/taginfo#3]
Values can only be simple strings not arrays for taginfo to understand them. See https://github.com/babykarte/taginfo/commit/3c18a8147a864c1b1216cf094b4a3d6d8ca7d122#diff-c929783c27b07907df6598747b61cd2095800d78a6175dea0c0c3c9798c40989R139 and other places in that commit.

**Comment by ValorNaram** [comment]
I prefer when other developers stick to standards and allow arrays as all do. Why are OSM products simply not obeying standards?

**Fixed not really a bug**
